spring:
  application:
    name: ChainCheck (Mock)
  task:
    scheduling:
      enabled: false

server:
  port: 8080

rpc:
  title: "Mock RPC"
  title-color: "#777777"
  get-safe-blocks: true
  get-finalized-blocks: true
  consensus:
    node-key: "mock-node-two"
  nodes:
    - name: Mock Node
      http: "http://mock.local"
      ws: "ws://mock.local"
      poll-interval-ms: 60000
      anomaly-detection:
        high-latency: 2000
    - name: Mock Node Two
      http: "http://mock-two.local"
      ws: "ws://mock-two.local"
      poll-interval-ms: 60000
      anomaly-detection:
        high-latency: 2600
